# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: github-package-repo automated build

on:
  push:
    paths:
    - 'github-package-repo/**'
    - '.github/workflows/github-package-repo-publish.yml'
  workflow_dispatch:

jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        java: [ 25 ]
        experimental: [false]
#        include:
#          - java: 25
#            experimental: true

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package -s $GITHUB_WORKSPACE/settings.xml --file github-package-repo/pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish to GitHub Packages Apache Maven
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/tags/*') &&  !matrix.experimental # Only run on main branch or tags and non-experimental
      run: mvn -B deploy jreleaser:full-release -P publication,release -s $GITHUB_WORKSPACE/settings.xml --file github-package-repo/pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        JRELEASER_GITHUB_TOKEN: ${{ github.token }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
        JRELEASER_GPG_PASSPHRASE : ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_RELEASE_DEPLOY_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
        JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_RELEASE_DEPLOY_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
        JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
        JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
      continue-on-error: true # Job continues even if this step fails

    - name: Display JReleaser trace
      run: cat target/jreleaser/trace.log
        
    - name: Display JReleaser properties
      run: cat target/jreleaser/output.properties
        
